server:
  port: 8080
  error:
    include-stacktrace: on-param

logging:
  level:
    web: debug

spring:
  host1: "http://localhost:4200"
  host2: "http://localhost:80"
  application:
    name: inaluma-makeup
  datasource:
    # url: jdbc:mysql://inaluma-db-anew:3306/inaluma_db_anew?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=Africa/Luanda
    url: jdbc:mysql://localhost:3306/inaluma_db_anew?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=Africa/Luanda
    username: inaluma
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          "[batch_size]": 30
        dialect: org.hibernate.dialect.MySQLDialect
        "[enable_lazy_load_no_trans]": true # solves "No Session JSON Parse exception" 

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
      resolve-lazily: false
      enabled: true
      file-size-threshold: 2KB